/**
  ******************************************************************************
  * @file    ai_dpu.h
  * @author  MCD Application Team
  * @version V2.2.0
  * @date    12-Jan-2025
  * @brief   This file is implementing ai processing functions that are making
  * 		 use of libraries generated by X-CUBE-AI
  ******************************************************************************
  * @attention
  *
  * Copyright (c) 2023-2025 STMicroelectronics.
  * All rights reserved.
  *
  * This software is licensed under terms that can be found in the LICENSE file
  * in the root directory of this software component.
  * If no LICENSE file comes with this software, it is provided AS-IS.
  *
  ******************************************************************************
  */


/* Define to prevent recursive inclusion -------------------------------------*/
#ifndef _AI_DPU_H
#define _AI_DPU_H

/* Includes ------------------------------------------------------------------*/
#include "main.h"
#include "dpu_config.h"
#include "ll_aton_runtime.h"
// #include "ai_wrapper_ATON.h"
#include "ai_platform.h"
#include "stai_network.h"
#include "aiTestUtility.h"

#define AI_DPU_X_CUBE_AI_API_MAJOR (1)
#define AI_DPU_X_CUBE_AI_API_MINOR (0)
#define AI_DPU_X_CUBE_AI_API_MICRO (0)
#define AI_DPU_NB_MAX_INPUT        (1U)
#define AI_DPU_NB_MAX_OUTPUT       (1U)

#define AI_DPU_CHANNEL_LAST

#ifdef AI_DPU_CHANNEL_LAST
#define AI_DPU_BATCH       (0)
#define AI_DPU_WIDTH       (1)
#define AI_DPU_HEIGHT      (2)
#define AI_DPU_CHANNEL     (3)
#endif

/* Exported constants --------------------------------------------------------*/
#define AI_MNETWORK_NUMBER         (1U)
#define AI_DPU_SHAPE_SIZE          (4U)
#define AI_DPU_SHAPE_BATCH_MAX     (1U)
#define AI_DPU_SHAPE_HEIGHT_MAX    (100U)
#define AI_DPU_SHAPE_WIDTH_MAX     (300U)
#define AI_DPU_SHAPE_CHANNEL_MAX   (100U)
#define AI_DPU_NB_MAX_INPUT        (1U)
#define AI_DPU_NB_MAX_OUTPUT       (1U)
#define AI_DPU_IO_BUFFER_MAX       (6U)

typedef struct {
  /* Global handle to reference the instantiated C-model */
  stai_network * p_network ;
  stai_ptr     * p_stai_inputs;
  stai_ptr     * p_stai_outputs;

  stai_network_info info;

  uint32_t sensor_type;                         /* Specifies AI data nature. */
  stai_format input_format;   /* input format, output format is always float */
  float  input_Q_inv_scale;                  /* quantization scale parameter */
  int16_t input_Q_offset;                   /* quantization offset parameter */
  int in_height;
  int in_width;
  int out_height;
  const char ** classes;
}AIProcCtx_t;

/* Exported functions --------------------------------------------------------*/
DPU_StatusTypeDef AiDPULoadModel(AIProcCtx_t * pxCtx);
DPU_StatusTypeDef AiDPUReleaseModel(AIProcCtx_t * pxCtx);
DPU_StatusTypeDef AiDPUProcess(AIProcCtx_t *pxCtx);

#endif /* _AI_DPU_H */
