/**
  ******************************************************************************
  * @file    ai_dpu.c
  * @author  MCD Application Team
  * @version V2.2.0
  * @date    12-Jan-2025
  * @brief   This file is implementing ai processing functions that are making
  * 		 use of libraries generated by X-CUBE-AI
  ******************************************************************************
  * @attention
  *
  * Copyright (c) 2023-2025 STMicroelectronics.
  * All rights reserved.
  *
  * This software is licensed under terms that can be found in the LICENSE file
  * in the root directory of this software component.
  * If no LICENSE file comes with this software, it is provided AS-IS.
  *
  ******************************************************************************
  */

/* Includes ------------------------------------------------------------------*/
#include "logging.h"

/* Standard includes. */
#include <string.h>
#include <stdio.h>

#include "ai_dpu.h"
#include "aiTestHelper_ST_AI.h"

#ifdef APP_BARE_METAL
#include "cpu_stats.h"
#endif

STAI_NETWORK_CONTEXT_DECLARE(network, STAI_NETWORK_CONTEXT_SIZE)
static stai_ptr stai_inputs[STAI_NETWORK_IN_NUM];
static stai_ptr stai_outputs[STAI_NETWORK_OUT_NUM];

/**
 * @brief Check if model can be supported by app
 * @param pxInfo:  pointer to network info
 * @retval DPU_OK if success, DPU_ERROR else
 */
static DPU_StatusTypeDef AiDPUCheckModel(stai_network_info *pxInfo)
{
  assert_param(pxInfo != NULL);
  DPU_StatusTypeDef res = DPU_OK;

  if (pxInfo->api_version.major != AI_DPU_X_CUBE_AI_API_MAJOR ||\
      pxInfo->api_version.minor != AI_DPU_X_CUBE_AI_API_MINOR ||\
      pxInfo->api_version.micro != AI_DPU_X_CUBE_AI_API_MICRO)
  {
    LogError("AI_DPU: Incompatible AI API version \n\r");
    res = DPU_ERROR;
  }
  if (pxInfo->api_version.major != AI_DPU_X_CUBE_AI_API_MAJOR ||\
      pxInfo->api_version.minor != AI_DPU_X_CUBE_AI_API_MINOR ||\
      pxInfo->api_version.micro != AI_DPU_X_CUBE_AI_API_MICRO)
  {
    LogError("AI_DPU: Incompatible AI API version \n\r");
    res = DPU_ERROR;
  }
  if (pxInfo->n_inputs > AI_DPU_NB_MAX_INPUT )
  {
    LogError("AI_DPU: Too many input tensors \n\r");
    res = DPU_ERROR;
  }
  if (pxInfo->n_outputs > AI_DPU_NB_MAX_OUTPUT )
  {
    LogError("AI_DPU: Too many output tensors\n\r");
    res = DPU_ERROR;
  }
  if (!(pxInfo->flags & STAI_FLAG_INPUTS) )
  {
    LogError("AI_DPU: --no-inputs-allocation not yet supported  \r\n");
    res = DPU_ERROR;
  }
  if (!(pxInfo->flags & STAI_FLAG_OUTPUTS) )
  {
    LogError("AI_DPU: --no-outputs-allocation not yet supported  \r\n");
    res = DPU_ERROR;
  }
  if (pxInfo->flags & STAI_FLAG_ACTIVATIONS)
  {
    LogWarn("AI_DPU: Activation are already allocated \r\n");
  }
  for (int i=0; i< pxInfo->n_inputs ; i++ )
  {
    if (STAI_FORMAT_S8 != pxInfo->inputs[i].format &&\
        STAI_FORMAT_FLOAT32 != pxInfo->inputs[i].format &&\
        4 != pxInfo->inputs[i].shape.size &&\
        !(pxInfo->inputs[i].flags & STAI_FLAG_CHANNEL_LAST) )
    {
      LogError("AI_DPU: Input format not supported\n\r");
      res = DPU_ERROR;
    }
  }
  for (int i=0; i< pxInfo->n_outputs ; i++ )
  {
    if (STAI_FORMAT_FLOAT32 != pxInfo->outputs[i].format &&\
        2 != pxInfo->outputs[i].shape.size)
    {
      LogError("AI_DPU: Output format not supported\n\r");
      res = DPU_ERROR;
    }
  }
  return res;
}

/* External functions --------------------------------------------------------*/
/**
 * @brief checks and loads AI model
 * @param pxInfo:  pointer to AI DPU context
 * @retval DPU_OK if success, DPU_ERROR else
 */
DPU_StatusTypeDef AiDPULoadModel(AIProcCtx_t * pxCtx)
{
  assert_param(pxCtx != NULL);
  stai_size _dummy;
  stai_return_code stai_err;

  pxCtx->p_network        = (stai_network *)network;
  pxCtx->p_stai_inputs    = stai_inputs;
  pxCtx->p_stai_outputs   = stai_outputs;
  pxCtx->sensor_type      = CTRL_X_CUBE_AI_SENSOR_TYPE;

  /* display AI platform version */
  stai_platform_version();

  /* Runtime initialization */
  stai_err = stai_runtime_init();
  if (STAI_SUCCESS != stai_err )
  {
    stai_log_err(stai_err, "stai_runtime_init");
    return DPU_ERROR;
  }

  /* Initialize the instance */
  stai_err =  stai_network_init(pxCtx->p_network);
  if (STAI_SUCCESS != stai_err )
  {
    stai_log_err(stai_err, "stai_network_init");
    return DPU_ERROR;
  }

  stai_network_get_info(pxCtx->p_network, &pxCtx->info);
  if (DPU_OK != AiDPUCheckModel(&pxCtx->info))
  {
    LogError("AI_DPU: Check model Failed \n\r");
    Error_Handler();
  }

  /* Set IO ----------------------------------------------------------------- */
  stai_err = stai_network_get_inputs(pxCtx->p_network, pxCtx->p_stai_inputs, &_dummy);
  if (STAI_SUCCESS != stai_err )
  {
    stai_log_err(stai_err, "stai_network_get_inputs");
    return DPU_ERROR;
  }
  stai_err = stai_network_get_outputs(pxCtx->p_network, pxCtx->p_stai_outputs, &_dummy);
  if (STAI_SUCCESS != stai_err )
  {
    stai_log_err(stai_err, "stai_network_get_outputs");
    return DPU_ERROR;
  }

  if ( STAI_FORMAT_S8 == pxCtx->info.inputs[0].format )
  {
    pxCtx->input_Q_inv_scale = 1/ pxCtx->info.inputs[0].scale.data[0];
    pxCtx->input_Q_offset = pxCtx->info.inputs[0].zeropoint.data[0];
  }


  assert_param ( 1 == pxCtx->info.n_inputs );  /* already checked in AudioPipeline_AICheckModel */
  assert_param ( 1 == pxCtx->info.n_outputs ); /* already checked in AudioPipeline_AICheckModel */

  pxCtx->in_width   = pxCtx->info.inputs[0].shape.data[AI_DPU_WIDTH];
  pxCtx->in_height  = pxCtx->info.inputs[0].shape.data[AI_DPU_HEIGHT];
  pxCtx->out_height = pxCtx->info.outputs[0].shape.data[AI_DPU_HEIGHT];

  LogInfo("\n\r");

  stai_log_network_infos(pxCtx->p_network);

  return DPU_OK;
}

/**
 * @brief Releases AI model
 * @param pxInfo:  pointer to AI DPU context
 * @retval DPU_OK if success, DPU_ERROR else
 */
DPU_StatusTypeDef AiDPUReleaseModel(AIProcCtx_t * pxCtx)
{
  assert_param( NULL != pxCtx );

  /* Deinitialize network model context */
  if ( STAI_SUCCESS != stai_network_deinit(pxCtx->p_network) )
  {
    LogError("AiDPUReleaseModel: network de-init failed \n\r");
    return DPU_ERROR;
  };

  /* Deinitialize runtime library */
  if ( STAI_SUCCESS != stai_runtime_deinit() )
  {
    LogError("AiDPUReleaseModel: STAI runtime de-init failed \n\r");
    return DPU_ERROR;
  };
  return DPU_OK;
}

/**
 * @brief Processes Data into AI model
 * @param pxInfo:  pointer to AI DPU context
 * @param pxInfo:  pointer to output array
 * @retval DPU_OK if success, DPU_ERROR else
 */
DPU_StatusTypeDef AiDPUProcess(AIProcCtx_t *pxCtx)
{
  assert_param( NULL != pxCtx );
  stai_return_code return_code;

  port_dwt_reset();
  return_code = stai_network_run(pxCtx->p_network, STAI_MODE_SYNC);
  if ( STAI_SUCCESS != return_code )
  {
    stai_log_err(return_code, "stai_network_run");
    return DPU_ERROR;
  }
#ifdef APP_BARE_METAL
  time_stats_store(TIME_STAT_AI_PROC,port_dwt_get_cycles()*1000.0F/port_hal_get_cpu_freq());
#endif
  return DPU_OK;
}
